package echo

// Response is the default response format.
type Response struct {
	// Describes api status or response code.
	Code string `json:"api_code"`

	// Describes status message that should be shown to user.
	DisplayMsg string `json:"api_display_message"`

	// Describes server real error message that should not be shown to user.
	RawMsg string `json:"api_raw_message"`

	// Used for debugging.
	// It uses client request `X-Request-ID` header.
	// If empty, generated by server instead.
	RequestID string `json:"trace_id"`

	// Describes current api generated result data.
	ResultData any `json:"api_result_data"`
}

// GetResultData is the default response result data format.
// For method GET.
type GetResultData struct {
	// Contains query param passed by client.
	// To cross check if server accept the correct param from client.
	Param any `json:"http_param"`

	// Defines the current API response generated.
	GeneratedDate string `json:"generated_date"`

	// Describes total number of data generated by current request.
	TotalData string `json:"total_data"`

	// Request result data.
	Data any `json:"data"`
}

// PostResultData is the default response result data format.
// For method PUT, PATCH, POST, DELETE.
type PostResultData struct {
	// Contains json body passed by client.
	// To cross check if server accept the correct param from client.
	Param any `json:"http_param"`

	// Defines the current API request execution time.
	ExecutedDate string `json:"executed_date"`

	// Describes total number of data is affected by current request.
	RowsAffected int `json:"rows_affected"`
}
